name: Swift

on:
  pull_request:
    types: [opened, reopened]
  push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -project UndoRedoApp.xcodeproj -scheme "UndoRedoApp (macOS)"
    - name: Run tests
      run: xcodebuild -project UndoRedoApp.xcodeproj -scheme "UndoRedoApp (macOS)" test
